# SPDX-License-Identifier:	GPL-2.0+
#
# Copyright 2020 MicroSys Electronics GmbH
# Author: Kay Potthoff <kay.potthoff@microsys.de>
#
#

obj-y += ddr.o
obj-y += comels1046a.o
obj-$(CONFIG_SYS_DPAA_FMAN) += eth.o
obj-$(CONFIG_LAYERSCAPE_NS_ACCESS) += ../../freescale/common/ns_access.o
obj-$(CONFIG_ID_EEPROM)	+= ../../freescale/common/sys_eeprom.o
