#
# Copyright 2015 Freescale Semiconductor
# (C) Copyright 2018 MicroSys Electronics GmbH
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ddr.o
obj-y += mpxls1043.o
obj-$(CONFIG_SYS_DPAA_FMAN) += eth.o
obj-$(CONFIG_SYS_DPAA_FMAN) += ../common/eth_common.o
obj-$(CONFIG_LAYERSCAPE_NS_ACCESS) += ../../freescale/common/ns_access.o
obj-$(CONFIG_ID_EEPROM)	+= ../../freescale/common/sys_eeprom.o
