#
# Copyright 2018 NXP
# Copyright (C) 2019 MicroSys Electronics GmbH
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += mpxls1028.o
obj-y += ddr.o
obj-$(CONFIG_ID_EEPROM)	+= ../../freescale/common/sys_eeprom.o
